<Project Sdk="Microsoft.NET.Sdk.Worker"><PropertyGroup><TargetFramework>net10.0-windows</TargetFramework></PropertyGroup><ItemGroup><ProjectReference Include="../SecurePrintManager.Core/SecurePrintManager.Core.csproj"/><ProjectReference Include="../SecurePrintManager.Database/SecurePrintManager.Database.csproj"/><PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.0"/></ItemGroup></Project>